### PR TITLE
feat: add `timeout_ms` field to SDKs

### PR DESCRIPTION
**Pull request by zshipko**

### CODE REVIEW

**Review by nilslice — APPROVED** [review]

**Comment by nilslice** [comment]
oops, didn't notice the c++ CI fail

**Comment by zshipko** [comment]
I am trying to figure that out, when I tested locally on macOS it was fine, so I’ll have to do some CI debugging to see what’s going on.

**Comment by zshipko** [comment]
Alright, I think this is in good shape now - the C++ `timeout_ms` was being set to 0 by default. I will merge this if CI passes.

**Comment by nilslice** [comment]
I'm gonna go learn c++, be back in 20 years

**Pull request merged**
