### PR TITLE
fix(rust): use CString for strings passed to to set_log_file

### PR DESCRIPTION
**Pull request by zshipko**

### CODE REVIEW

**Comment by bhelx** [comment]
This should work right?

```rust
// host
set_log_file("stdout", Some(log::Level::Trace));
```

```rust
// plugin
info!("Hello World!");
```

Still doesn't seem to be working for me

**Comment by zshipko** [comment]
Does `set_log_file` return `true` or `false`?

**Comment by bhelx** [comment]
It's returning `false`

**Comment by zshipko** [comment]
thanks, i was able to replicate it and just pushed up a fix.

**Comment by bhelx** [comment]
Works now!

**Review by bhelx — APPROVED** [review]

**Pull request merged**
