### PR TITLE
feat(zig-sdk): Implement Host Functions

### PR DESCRIPTION
**Pull request by usdogu**
There are some breaking changes:

- Plugin.init now requires an allocator and functions slice
- Plugin.initFromManifest now requires a functions slice
- Plugin struct removed in favor of using the file as struct
  - from @nilslice: https://zig.news/gowind/zig-files-are-structs-288j (good reference!)

### CODE REVIEW

**Comment by usdogu** [comment]
It should be done now, the check randomly fails because of threads

**Comment by nilslice** [comment]
Awesome, @usdogu - thank you!

I will test this out and get back to you asap.

**Comment by nilslice** [comment]
I have TODOs to update the extism.org docs with the latest build.zig configuration from this PR.

**Comment by nilslice** [comment]
It seems (based on [this comment](https://github.com/ziglang/zig/blob/3c2a43fdcc2d9aeafafe7ef37c7b805e18fac351/lib/std/Thread.zig#L330-L331)) that there was just a minor missing step to ensure the Thread resources were cleaned up. 

`detach` could also probably be used here to more closely demonstrate the effect of assigning the Thread to `_` as previously done. If CI passes with this change, it's good enough for me ;)

**Review by nilslice — APPROVED** [review]
:rocket: awesome work, @usdogu!

**Comment by nilslice** [comment]
Updated docs: https://extism.org/docs/integrate-into-your-codebase/zig-host-sdk/

@usdogu, if you have some time to review, please let me know if you see anything incorrect there. Thanks!

**Comment by usdogu** [comment]
@nilslice, In build.zig

```diff
--- old.zig     2023-02-13 00:08:40.411043737 +0300
+++ build.zig   2023-02-13 00:10:27.331042426 +0300
@@ -4,21 +4,21 @@
     const target = b.standardTargetOptions(.{});
     const optimize = b.standardOptimizeOption(.{});
     const exe = b.addExecutable(.{
-        .root_source_file = "src/main.zig",
+        .root_source_file = .{ .path = "src/main.zig" },
         .target = target,
         .optimize = optimize,
     });

     // Add the `extism` library from the cloned repository
-    exe.addAnonymousModule("extism", .{ .source_file = .{ .path = "src/main.zig" } });
+    exe.addAnonymousModule("extism", .{ .source_file = .{ .path = "libs/extism/zig/src/main.zig" } });
     exe.linkLibC();

@@ -30,9 +30,11 @@
     const run_step = b.step("run", "Run the app");
     run_step.dependOn(&run_cmd.step);

-    const exe_tests = b.addTest("src/main.zig");
-    exe_tests.setTarget(target);
-    exe_tests.setBuildMode(mode);
+    var exe_tests = b.addTest(.{
+       .root_source_file = .{ .path = "src/main.zig" },
+       .target = target,
+       .optimize = optimize
+    });

     const test_step = b.step("test", "Run unit tests");
     test_step.dependOn(&exe_tests.step);
```

**Comment by nilslice** [comment]
Updated -- thank you for catching the path issue, and fixing the test config! I'm always learning more about Zig :)

**Pull request merged**
