### PR TITLE
fix(zig-sdk): Fix Example And Test

### PR DESCRIPTION
**Pull request by usdogu**
See ziglang/zig#14638

### CODE REVIEW

**Review by nilslice — APPROVED** [review]
Awesome - thanks @usdogu! How do you keep on top of these changes to Zig? I'd like to follow more closely as much as I can.

**Comment by usdogu** [comment]
@nilslice, I just check the merged PRs everyday like a psychopath :)

**Comment by nilslice** [comment]
Haha alright I will try to do the same! 

So Zig auto-releases the latest build (and therefore is the same we use in our CI) after these changes are merged?

**Comment by usdogu** [comment]
It auto-releases a new version every day, even if there are no changes

**Pull request merged**
