### PR TITLE
Fix large allocations (missing commits)

### PR DESCRIPTION
**Pull request by zshipko**

### CODE REVIEW

**Comment by zshipko** [comment]
@nilslice: here are the missing commits from the other PR

**Comment by zshipko** [comment]
I just fixed the broken Python test, so I think this is ready if CI passes.

**Comment by nilslice** [comment]
Ok awesome, thank you!

**Comment by zshipko** [comment]
Sorry, I actually have a better fix for the last commit I made, give me a sec to update it. I will let you know when aim done.

**Comment by nilslice** [comment]
No worries -- gonna step afk for a few. just ping me on discord whenever!

**Comment by zshipko** [comment]
Okay, I'm done for the night, feel free to merge when you're back online.

**Pull request merged**
