### PR TITLE
feat(runtime): support log_trace in rust-sdk

### PR DESCRIPTION
**Pull request by hilaryRope**
## Description of the change
Add support for logtrace in Rust SDK runtime

## Issue Reference
https://github.com/extism/extism/issues/744 that is a logical step after [this](https://github.com/extism/go-pdk/issues/37)

## Checklist
- [] Documentation added/updated

### CODE REVIEW

**Comment by nilslice** [comment]
it looks like the failing `clippy` lints are unrelated to your change, so I'll look back at recent PRs to see if something may have been updated with the lint settings to cause this now. 

also, I updated your PR title (which becomes the commit message when this is merged) to follow [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), to which we _try_ to conform as often as possible. Not a major thing, just pointing it out in case you'd like to read up! :)

**Comment by nilslice** [comment]
Ok, it appears that these are all fairly recent additions (my Rust 1.77 had no issues, but updating to latest 1.80 does). 

I will make the changes that `clippy` suggests, or appropriately skip them if need be.

**Comment by nilslice** [comment]
@chrisdickinson / @bhelx would you take a quick look here? as long as you don't mind just suppressing the specific `clippy` lints for the time being, I think we can merge this. For context, these are new lints that didn't impact recent versions of Rust until the latest release it seems.

**Comment by chrisdickinson** [comment]
(I'm taking a look at fixing the clippy warnings in a commit so we can leave the lint on)

**Comment by chrisdickinson** [comment]
Switching to mutable reborrows to address the lint improved a few benchmarks:

```
basic/basic             time:   [6.3545 ms 6.3712 ms 6.3929 ms]
                        change: [-7.0116% -4.9256% -3.1801%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 9 outliers among 100 measurements (9.00%)
  4 (4.00%) high mild
  5 (5.00%) high severe

count_vowels/count_vowels(4096)
                        time:   [49.073 µs 49.188 µs 49.310 µs]
                        change: [-2.0943% -1.5450% -1.0911%] (p = 0.00 < 0.05)
                        Performance has improved.
```

(Admittedly only by a _tiiiny_ bit, but hey, bonus!)

Thanks for picking up this work, @hilaryRope!

**Comment by nilslice** [comment]
love to see it!

**Review by chrisdickinson — APPROVED** [review]
LGTM! Now to wait for the tests to pass... ⏲️

**Comment by hilaryRope** [comment]
Thank you all for this!

**Pull request merged**
