### PR TITLE
Refactor java-sdk

### PR DESCRIPTION
**Pull request by thomasdarimont**
- Refactor Plugin
- Make `Plugin` and `Context`  `AutoClosable` to automatically free resources in TWR blocks
- Add missing javadoc
- Upgrade to Junit 5
- Reorganize packages
- Use more meaningful names
- Introduce `ExtismException`
- Make JSON serialization pluggable
- Lower required java version to Java 17

Improves #117

### CODE REVIEW

**Comment by thomasdarimont** [comment]
@bhelx I just gave this another spin and refactored the library to be a bit. Hope this meets your expectations. :)

I think we could also lower the required Java version to Java 17.

**Comment by bhelx** [comment]
Hey @thomasdarimont we seem to be simultaneously working on the same stuff today. Happy to take your changes many of them look better than mine. If you want to take on some of the rest of the work though let me know so I don't step on your toes. Happy to have you lead here! :)

**Comment by bhelx** [comment]
> I think we could also lower the required Java version to Java 17.

yeah let's go as low as we can safely go!

**Comment by bhelx** [comment]
Let me know if you want to resolve the conflicts or me. I think it's safe to say I prefer your changes.

**Comment by thomasdarimont** [comment]
Sorry for the overlap. I'll try to merge it quickly.

**Comment by thomasdarimont** [comment]
@bhelx I just finished the merge. I reused most of your JavaDoc comments and added some convenience methods. 
I also made the `Context` class `AutoClosable` to leverage automatic resource cleanup in TWR blocks.

I saw that you made some methods protected, for which I wasn't sure whether they are intended for internal usage or usage by subclasses. Feel free to adapt the code to your liking :^)

**Comment by bhelx** [comment]
Thanks again! Is there anything else you had planned on working on? I actually think it's pretty close to being good for a release. I'm gonna setup CI and publishing next. If you have anything you're interested in doing let me know.

**Comment by thomasdarimont** [comment]
Thanks @bhelx for the quick turnaround :) I just added some additional remarks on the java-sdk PR. 
I give the project another look towards the weekend :)

**Pull request merged**
