### PR TITLE
ci: release extism.dll.lib and extism.dll.a

### PR DESCRIPTION
**Pull request by mhmd-azeez**
Related to #141 and #584 
Follow up of #632

### CODE REVIEW

**Comment by mhmd-azeez** [comment]
Here is a sample project that shows this works:
https://github.com/mhmd-azeez/extism-cpp-demo

**Review by G4Vi — APPROVED** [review]
LGTM, thank you! At some point we should test building with mingw. It's good to have all the import libraries.

**Review by chrisdickinson — APPROVED** [review]
LGTM! Great work.

**Review by chrisdickinson — APPROVED** [review]
Github didn't clear my notifications with that last LGTM, so you get two LGTMs from me! 😅

**Pull request merged**
