### PR TITLE
refactor: Update dependencies in java maven module and cleanup code

### PR DESCRIPTION
**Pull request by thomasdarimont**
- Update maven-plugins in pom.xml
- Update dependency versions in pom.xml
- Remove model-assert (test) dependency to avoid using libraries with knwon CVEs
- Replaced model-assert with assertj+gson
- Removed unused imports
- Made pointer field in ExtismCurrentPlugin private final
- Made handle field in CancelHandle private final and exposed the cancel method (since it is a public type)

### CODE REVIEW

**Comment by bhelx** [comment]
Hey @thomasdarimont, really appreciate these changes! Do you mind porting them to https://github.com/extism/java-sdk ? We're moving the SDKs to their own repo for 1.0

**Comment by bhelx** [comment]
If you don't have time I can attempt to move them over

**Comment by thomasdarimont** [comment]
@bhelx I just sent a PR with this changes to the other repository: https://github.com/extism/java-sdk/pull/12

**Comment by thomasdarimont** [comment]
@bhelx in order to test the stuff in the other repo, you need to approve the new PR :)

**Comment by thomasdarimont** [comment]
Closed in favour of https://github.com/extism/java-sdk/pull/12

**Pull request closed without merging**
